version: '3'
services:
  mirai:
    image: sttot/mirai:latest
    restart: always
    privileged: true
    tty: true
    stdin_open: true
    ports:
      - 5700:5700
    volumes:
      - ./mirai:/mymirai
    command:
        - sh
        - -c
        - |
            if [ ! -f /mirai_copied.lock ]; then
                mv /mirai/* /mymirai/
                rm -rf /mirai
                ln -s /mymirai /mirai
                touch /mirai_copied.lock
            fi
            cd /mirai
            java -Dmirai.slider.captcha.supported -jar mcl.jar
    # healthcheck:
    #     test: ["CMD", "curl", "-f", "http://localhost"] # 设置检测程序
    #     interval: 1m30s # 设置检测间隔
    #     timeout: 10s # 设置检测超时时间
    #     retries: 3 # 设置重试次数
    #     start_period: 40s # 启动后，多少秒开始启动检测程序
