version: '3'
services:
  mirai:
    image: registry.cn-hangzhou.aliyuncs.com/sttot/mirai:latest
    restart: always
    privileged: true
    stdin_open: true
    tty: true
    ports:
      - 5700:5700
      - 18080:8080
    volumes:
      - ./mirai:/mirai
    command: ['bash', '-c', '/mirai/mcl']
